DROP TABLE Show CASCADE CONSTRAINTS;
DROP TABLE Show_Award CASCADE CONSTRAINTS;
DROP TABLE Show_Vid CASCADE CONSTRAINTS;
DROP TABLE Show_Photo CASCADE CONSTRAINTS;
DROP TABLE Show_Genre CASCADE CONSTRAINTS;
DROP TABLE Episode CASCADE CONSTRAINTS;
DROP TABLE Writer CASCADE CONSTRAINTS;
DROP TABLE Written_By CASCADE CONSTRAINTS;
DROP TABLE Actor CASCADE CONSTRAINTS;
DROP TABLE Actor_Award CASCADE CONSTRAINTS;
DROP TABLE Actor_Vid CASCADE CONSTRAINTS;
DROP TABLE Actor_Photo CASCADE CONSTRAINTS;
DROP TABLE Actor_Role CASCADE CONSTRAINTS;
DROP TABLE Actor_Cast CASCADE CONSTRAINTS;
DROP TABLE Studio CASCADE CONSTRAINTS;
DROP TABLE Studio_Prevprod CASCADE CONSTRAINTS;
DROP TABLE Studio_Filmloc CASCADE CONSTRAINTS;
DROP TABLE Studio_Produce CASCADE CONSTRAINTS;
DROP TABLE Reviewer CASCADE CONSTRAINTS;
DROP TABLE Reviewer_Other CASCADE CONSTRAINTS;
DROP TABLE Reviewer_Review CASCADE CONSTRAINTS;
DROP TABLE Director CASCADE CONSTRAINTS;
DROP TABLE Director_Award CASCADE CONSTRAINTS;
DROP TABLE Director_Vid CASCADE CONSTRAINTS;
DROP TABLE Director_Photo CASCADE CONSTRAINTS;
DROP TABLE Director_Works CASCADE CONSTRAINTS;
DROP TABLE Director_Direct CASCADE CONSTRAINTS;
DROP TABLE Songs CASCADE CONSTRAINTS;
DROP TABLE Song_Artist CASCADE CONSTRAINTS;
DROP TABLE Song_Genre CASCADE CONSTRAINTS;


CREATE TABLE Show(
Id		VARCHAR2(9),
Title		VARCHAR2(50),
Age_Rate	VARCHAR2(4),
Summary		VARCHAR2(500),
CONSTRAINT Show_Id_Title_PK PRIMARY KEY(Id, Title));

CREATE TABLE Show_Award(
Id		VARCHAR2(9),
Award_Name 	VARCHAR2(25) CONSTRAINT Show_Award_Name_PK PRIMARY KEY);

CREATE TABLE Show_Vid(
Id		VARCHAR2(9),
Vid_Label 	VARCHAR2(25) CONSTRAINT Show_Vid_Label_PK PRIMARY KEY);

CREATE TABLE Show_Photo(
Id		VARCHAR2(9),
Photo_Label  	VARCHAR2(25) CONSTRAINT Show_Photo_Label_PK PRIMARY KEY);

CREATE TABLE Show_Genre(
Id		VARCHAR2(9),
Genre_Type  	VARCHAR2(25) CONSTRAINT Show_Genre_Type_PK PRIMARY KEY);

CREATE TABLE Episode(
Title 		VARCHAR2(50) CONSTRAINT Episode_Title_PK PRIMARY KEY,
No_Eps		NUMBER(4),
Season_No	NUMBER(3),
Date_Air	DATE,
Tv_Id		VARCHAR2(9));

CREATE TABLE Writer(
Id 		VARCHAR2(9) CONSTRAINT Writer_Id_PK PRIMARY KEY,
Name		VARCHAR2(30),
Birthdate	DATE);

CREATE TABLE Written_By(
Tv_Id		VARCHAR2(9),
Writer_Id	VARCHAR2(9));

CREATE TABLE Actor(
Id 		VARCHAR2(9) CONSTRAINT Actor_Id_PK PRIMARY KEY,
Name		VARCHAR2(30),
Birthdate	DATE);

CREATE TABLE Actor_Award(
Id		VARCHAR2(9),
Award_Name 	VARCHAR2(25) CONSTRAINT Actor_Award_Name_PK PRIMARY KEY);

CREATE TABLE Actor_Vid(
Id		VARCHAR2(9),
Vid_Label 	VARCHAR2(25) CONSTRAINT Actor_Vid_Label_PK PRIMARY KEY);

CREATE TABLE Actor_Photo(
Id		VARCHAR2(9),
Photo_Label 	VARCHAR2(25) CONSTRAINT Actor_Photo_Label_PK PRIMARY KEY);

CREATE TABLE Actor_Role(
Id		VARCHAR2(9),
Show_Name 	VARCHAR2(50) CONSTRAINT Actor_Role_Show_Name_PK PRIMARY KEY);

CREATE TABLE Actor_Cast(
Tv_Id		VARCHAR2(9),
Actor_Id	VARCHAR2(9),
Character	VARCHAR2(30));

CREATE TABLE Studio(
Id		VARCHAR2(9),
Name		VARCHAR2(30),
CONSTRAINT Studio_Id_Name_PK PRIMARY KEY(Id, Name));

CREATE TABLE Studio_Prevprod(
Id		VARCHAR2(9),
Prev_Prod 	VARCHAR2(30) CONSTRAINT Studio_Prevpod_Prev_Prod_PK PRIMARY KEY);

CREATE TABLE Studio_Filmloc(
Id		VARCHAR2(9),
Country		VARCHAR2(20),
City		VARCHAR2(25),
Address		VARCHAR2(50),
CONSTRAINT Studio_Filmloc_CounCityAdd_PK PRIMARY KEY(Country, City, Address));

CREATE TABLE Studio_Produce(
Tv_Id		VARCHAR2(9),
Studio_Id	VARCHAR2(9));

CREATE TABLE Reviewer(
Id 		VARCHAR2(9) CONSTRAINT Reviewer_Id_PK PRIMARY KEY,
Name		VARCHAR2(30),
Type		CHAR (7));

CREATE TABLE Reviewer_Other(
Id		VARCHAR2(9),
Review_Text	VARCHAR2(300) CONSTRAINT Reviewer_Other_Review_Text_PK PRIMARY KEY);

CREATE TABLE Reviewer_Review(
Tv_Id		VARCHAR2(9),
Reviewer_Id	VARCHAR2(9),
Date_Post	DATE,
Rating		NUMBER(2, 1),
Review_Content	VARCHAR2(300));

CREATE TABLE Director(
Id		VARCHAR2(9) CONSTRAINT Director_Id_PK PRIMARY KEY,
Name		VARCHAR2(30),
Birthdate	DATE);

CREATE TABLE Director_Award(
Id		VARCHAR2(9),
Award_Name	VARCHAR2(25) CONSTRAINT Director_Award_Name_PK PRIMARY KEY);

CREATE TABLE Director_Vid(
Id		VARCHAR2(9),
Vid_Label	VARCHAR2(25) CONSTRAINT Director_Vid_Label_PK PRIMARY KEY);

CREATE TABLE Director_Photo(
Id		VARCHAR2(9),
Photo_Label	VARCHAR2(25) CONSTRAINT Reviewer_Photo_Id_PK PRIMARY KEY);

CREATE TABLE Director_Works(
Id		VARCHAR2(9),
Work_Name	VARCHAR2(50) CONSTRAINT Director_Work_Name_PK PRIMARY KEY);

CREATE TABLE Director_Direct(
Tv_Id		VARCHAR2(9),
Director_Id	VARCHAR2(9));

CREATE TABLE Songs(
Id		VARCHAR2(9) CONSTRAINT Songs_Id_PK PRIMARY KEY,
Song_Title	VARCHAR2(30),
Music_Type	VARCHAR2(30),
Tv_Id		VARCHAR2(9));

CREATE TABLE Song_Artist(
Id		VARCHAR2(9),
Name		VARCHAR2(30) CONSTRAINT Song_Artist_Name_PK PRIMARY KEY);

CREATE TABLE Song_Genre(
Id		VARCHAR2(9),
Genre_Type	VARCHAR2(25) CONSTRAINT Song_Genre_Type_PK PRIMARY KEY);


ALTER TABLE Show_Award
ADD CONSTRAINT Show_Award_Id_fk FOREIGN KEY(Id)
REFERENCES Show(Id);

ALTER TABLE Show_Vid
ADD CONSTRAINT Show_Vid_Id_fk FOREIGN KEY(Id)
REFERENCES Show(Id);

ALTER TABLE Show_Photo
ADD CONSTRAINT Show_Photo_Id_fk FOREIGN KEY(Id)
REFERENCES Show(Id);

ALTER TABLE Show_Genre
ADD CONSTRAINT Show_Genre_Id_fk FOREIGN KEY(Id)
REFERENCES Show(Id);

ALTER TABLE Episode
ADD CONSTRAINT Episode_Tv_Id_fk FOREIGN KEY(Tv_Id)
REFERENCES Show(Id);

ALTER TABLE Written_By
ADD CONSTRAINT Written_By_Tv_Id_fk FOREIGN KEY(Tv_Id)
REFERENCES Show(Id);

ALTER TABLE Written_By
ADD CONSTRAINT Written_By_Writer_Id_fk FOREIGN KEY(Writer_Id)
REFERENCES Writer(Id);

ALTER TABLE Actor_Award
ADD CONSTRAINT Actor_Award_Id_fk FOREIGN KEY(Id)
REFERENCES Actor(Id);

ALTER TABLE Actor_Vid
ADD CONSTRAINT Actor_Vid_Id_fk FOREIGN KEY(Id)
REFERENCES Actor(Id);

ALTER TABLE Actor_Photo
ADD CONSTRAINT Actor_Photo_Id_fk FOREIGN KEY(Id)
REFERENCES Actor(Id);

ALTER TABLE Actor_Role
ADD CONSTRAINT Actor_Role_Id_fk FOREIGN KEY(Id)
REFERENCES Actor(Id);

ALTER TABLE Actor_Cast
ADD CONSTRAINT Actor_Cast_Tv_Id_fk FOREIGN KEY(Tv_Id)
REFERENCES Show(Id);

ALTER TABLE Actor_Cast
ADD CONSTRAINT Actor_Cast_Actor_Id_fk FOREIGN KEY(Actor_Id)
REFERENCES Actor(Id);

ALTER TABLE Studio_Prevprod
ADD CONSTRAINT Studio_Prevprod_Id_fk FOREIGN KEY(Id)
REFERENCES Studio(Id);

ALTER TABLE Studio_Filmloc
ADD CONSTRAINT Studio_Filmloc_Id_fk FOREIGN KEY(Id)
REFERENCES Studio(Id);

ALTER TABLE Studio_Produce
ADD CONSTRAINT Studio_Produce_Tv_Id_fk FOREIGN KEY(Tv_Id)
REFERENCES Show(Id);

ALTER TABLE Studio_Produce
ADD CONSTRAINT Studio_Produce_Studio_Id_fk FOREIGN KEY(Studio_Id)
REFERENCES Studio(Id);

ALTER TABLE Reviewer_Other
ADD CONSTRAINT Reviewer_Other_Id_fk FOREIGN KEY(Id)
REFERENCES Reviewer(Id);

ALTER TABLE Reviewer_Review
ADD CONSTRAINT Reviewer_Review_Tv_Id_fk FOREIGN KEY(Tv_Id)
REFERENCES Show(Id);

ALTER TABLE Reviewer_Review
ADD CONSTRAINT Reviewer_Review_Rev_Id_fk FOREIGN KEY(Reviewer_Id)
REFERENCES Reviewer(Id);

ALTER TABLE Director_Award
ADD CONSTRAINT Director_Award_Id_fk FOREIGN KEY(Id)
REFERENCES Director(Id);

ALTER TABLE Director_Vid
ADD CONSTRAINT Director_Vid_Id_fk FOREIGN KEY(Id)
REFERENCES Director(Id);

ALTER TABLE Director_Photo
ADD CONSTRAINT Director_Photo_Id_fk FOREIGN KEY(Id)
REFERENCES Director(Id);

ALTER TABLE Director_Works
ADD CONSTRAINT Director_Works_Id_fk FOREIGN KEY(Id)
REFERENCES Director(Id);

ALTER TABLE Director_Direct
ADD CONSTRAINT Director_Direct_Tv_Id_fk FOREIGN KEY(Tv_Id)
REFERENCES Show(Id);

ALTER TABLE Director_Direct
ADD CONSTRAINT Director_Direct_Dir_Id_fk FOREIGN KEY(Director_Id)
REFERENCES Director(Id);

ALTER TABLE Songs
ADD CONSTRAINT Songs_Tv_Id_fk FOREIGN KEY(Tv_Id)
REFERENCES Show(Id);

ALTER TABLE Song_Artist
ADD CONSTRAINT Song_Artist_Id_fk FOREIGN KEY(Id)
REFERENCES Songs(Id);

ALTER TABLE Song_Genre
ADD CONSTRAINT Songs_Genre_Id_fk FOREIGN KEY(Id)
REFERENCES Songs(Id);
